// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Attachment metadata for persisted recruitment-family notices.
type Attachment struct {
	ID               int64       `json:"id"`
	NoticeID         pgtype.Int8 `json:"notice_id"`
	SourceDocumentID pgtype.Int8 `json:"source_document_id"`
	// ObjectStore record for the preserved original attachment.
	StoredObjectID   pgtype.Int8 `json:"stored_object_id"`
	BrdID            string      `json:"brd_id"`
	Seq              string      `json:"seq"`
	FileSeq          string      `json:"file_seq"`
	OriginalFilename string      `json:"original_filename"`
	FileExt          string      `json:"file_ext"`
	FileSize         int64       `json:"file_size"`
	ContentType      string      `json:"content_type"`
	PreviewUrl       string      `json:"preview_url"`
	DownloadUrl      string      `json:"download_url"`
	// Legacy local prototype path retained for compatibility until ObjectStore migration is complete.
	StoragePath string `json:"storage_path"`
	ObjectKey   string `json:"object_key"`
	Sha256      string `json:"sha256"`
	// Classified attachment role such as notice_pdf, housing_unit_list_xlsx, schedule_pdf, applicant_or_winner_file, application_form, or unsupported.
	AttachmentKind  string             `json:"attachment_kind"`
	ExtractorStatus string             `json:"extractor_status"`
	RawMetadata     []byte             `json:"raw_metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// Legacy prototype extraction rows retained for compatibility.
type AttachmentExtraction struct {
	ID           int64              `json:"id"`
	AttachmentID pgtype.Int8        `json:"attachment_id"`
	Extractor    string             `json:"extractor"`
	Status       string             `json:"status"`
	ExtractedAt  pgtype.Timestamptz `json:"extracted_at"`
	SheetName    string             `json:"sheet_name"`
	PageNo       pgtype.Int4        `json:"page_no"`
	RowNo        pgtype.Int4        `json:"row_no"`
	RawText      string             `json:"raw_text"`
	RawJson      []byte             `json:"raw_json"`
	ErrorText    string             `json:"error_text"`
}

// Pipeline execution record for discovery, extraction, normalization, and QA runs.
type CollectionRun struct {
	ID         int64              `json:"id"`
	Source     string             `json:"source"`
	Status     string             `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	// Run-level counters and reports. This is operational metadata, not the serving data model.
	Stats     []byte      `json:"stats"`
	ErrorText pgtype.Text `json:"error_text"`
}

// Mechanical extraction outputs from PDF, XLSX, HWP, or HTML before normalization.
type ExtractedArtifact struct {
	ID             int64       `json:"id"`
	AttachmentID   pgtype.Int8 `json:"attachment_id"`
	StoredObjectID pgtype.Int8 `json:"stored_object_id"`
	// Artifact kind such as xlsx_row, pdf_text, html_preview, hwp_unsupported, or table_candidate.
	ArtifactType  string      `json:"artifact_type"`
	Extractor     string      `json:"extractor"`
	Status        string      `json:"status"`
	SchemaVersion string      `json:"schema_version"`
	SheetName     string      `json:"sheet_name"`
	PageNo        pgtype.Int4 `json:"page_no"`
	RowNo         pgtype.Int4 `json:"row_no"`
	CellRef       string      `json:"cell_ref"`
	RawText       string      `json:"raw_text"`
	// Extractor payload for audit and reprocessing. Serving APIs should use normalized tables.
	ContentJson []byte `json:"content_json"`
	// Machine-readable or human-readable pointer to the source page, sheet, row, cell, or HTML selector.
	SourceSpan string             `json:"source_span"`
	Confidence pgtype.Numeric     `json:"confidence"`
	ErrorText  string             `json:"error_text"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Normalized individual housing unit records. A housing unit means a room or unit inside a building, not the building itself.
type HousingUnit struct {
	ID               int64       `json:"id"`
	NoticeID         pgtype.Int8 `json:"notice_id"`
	AttachmentID     pgtype.Int8 `json:"attachment_id"`
	SourceArtifactID pgtype.Int8 `json:"source_artifact_id"`
	Agency           string      `json:"agency"`
	Source           string      `json:"source"`
	// Supply category such as 신규공급 or 재공급 when provided by the source.
	SupplyCategory string `json:"supply_category"`
	// Original row/list number from a housing unit list attachment.
	ListNo string `json:"list_no"`
	// Seoul district extracted from the address, such as 영등포구.
	District string `json:"district"`
	// Full normalized address. This must not be left only in raw_row.
	Address string `json:"address"`
	// Legal dong candidate parsed from the address.
	LegalDong     string `json:"legal_dong"`
	AddressDetail string `json:"address_detail"`
	// Source housing name. This may overlap with complex_name in SH spreadsheets.
	HousingName  string `json:"housing_name"`
	ComplexName  string `json:"complex_name"`
	BuildingName string `json:"building_name"`
	// Unit or room number inside a building.
	UnitNo string      `json:"unit_no"`
	Floor  pgtype.Int4 `json:"floor"`
	// Floor number. The legacy floor column is retained for prototype compatibility.
	FloorNo           pgtype.Int4    `json:"floor_no"`
	UnitType          string         `json:"unit_type"`
	StructureType     string         `json:"structure_type"`
	ElevatorInstalled pgtype.Bool    `json:"elevator_installed"`
	ExclusiveAreaM2   pgtype.Numeric `json:"exclusive_area_m2"`
	AreaPyeong        pgtype.Numeric `json:"area_pyeong"`
	DepositText       string         `json:"deposit_text"`
	DepositAmount     pgtype.Numeric `json:"deposit_amount"`
	// Normalized deposit amount in KRW.
	DepositKrw        pgtype.Int8    `json:"deposit_krw"`
	MonthlyRentText   string         `json:"monthly_rent_text"`
	MonthlyRentAmount pgtype.Numeric `json:"monthly_rent_amount"`
	// Normalized monthly rent amount in KRW.
	MonthlyRentKrw pgtype.Int8 `json:"monthly_rent_krw"`
	SupplyCount    pgtype.Int4 `json:"supply_count"`
	Direction      string      `json:"direction"`
	Status         string      `json:"status"`
	SourceSheet    string      `json:"source_sheet"`
	SourceRow      pgtype.Int4 `json:"source_row"`
	SourceCell     string      `json:"source_cell"`
	SourcePage     pgtype.Int4 `json:"source_page"`
	// Evidence pointer for the normalized unit record.
	SourceSpan string `json:"source_span"`
	// Raw XLSX row evidence for audit and reprocessing, not the primary query model.
	RawRow     []byte         `json:"raw_row"`
	Confidence pgtype.Numeric `json:"confidence"`
	// Promotion state for serving. Only QA-approved records should be exposed by default.
	QaStatus  string             `json:"qa_status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Per-unit calculated estimates derived from rent conversion rules.
type HousingUnitConversionEstimate struct {
	ID                            int64       `json:"id"`
	HousingUnitID                 int64       `json:"housing_unit_id"`
	RentConversionRuleID          int64       `json:"rent_conversion_rule_id"`
	MaxConvertibleRentKrw         pgtype.Int8 `json:"max_convertible_rent_krw"`
	EstimatedAdditionalDepositKrw pgtype.Int8 `json:"estimated_additional_deposit_krw"`
	// Estimated minimum monthly rent after maximum rent-to-deposit conversion.
	EstimatedMinMonthlyRentKrw pgtype.Int8        `json:"estimated_min_monthly_rent_krw"`
	CalculationVersion         string             `json:"calculation_version"`
	SourceSpan                 string             `json:"source_span"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
}

// Constrained LLM repair attempts for low-confidence deterministic extraction segments.
type LlmRepairAttempt struct {
	ID            int64  `json:"id"`
	ArtifactID    int64  `json:"artifact_id"`
	SchemaVersion string `json:"schema_version"`
	PromptVersion string `json:"prompt_version"`
	Model         string `json:"model"`
	// Hash of the exact LLM input segment.
	InputHash  string         `json:"input_hash"`
	OutputHash string         `json:"output_hash"`
	Status     string         `json:"status"`
	Confidence pgtype.Numeric `json:"confidence"`
	// Required source evidence for accepting LLM output.
	SourceSpan   string             `json:"source_span"`
	RequestJson  []byte             `json:"request_json"`
	ResponseJson []byte             `json:"response_json"`
	ErrorText    string             `json:"error_text"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Structured notice schedules such as application, document submission, winner announcement, contract, and move-in.
type NoticeSchedule struct {
	ID               int64              `json:"id"`
	NoticeID         int64              `json:"notice_id"`
	SourceArtifactID pgtype.Int8        `json:"source_artifact_id"`
	ScheduleType     string             `json:"schedule_type"`
	Label            string             `json:"label"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	// Original date expression retained for review when parsed timestamps are partial or ambiguous.
	DateText   string `json:"date_text"`
	Channel    string `json:"channel"`
	Note       string `json:"note"`
	SourceText string `json:"source_text"`
	// Evidence pointer for the schedule extraction.
	SourceSpan string             `json:"source_span"`
	Confidence pgtype.Numeric     `json:"confidence"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// QA gate decisions controlling promotion to serving/API models.
type QaDecision struct {
	ID         int64  `json:"id"`
	TargetType string `json:"target_type"`
	TargetID   int64  `json:"target_id"`
	// Decision value such as approved, rejected, quarantined, or needs_review.
	Decision string `json:"decision"`
	Reason   string `json:"reason"`
	// Structured QA check results with exact failure reasons and measured values.
	ChecksJson []byte             `json:"checks_json"`
	DecidedAt  pgtype.Timestamptz `json:"decided_at"`
	DecidedBy  string             `json:"decided_by"`
}

// Fetched HTTP documents kept as audit and reprocessing evidence.
type RawDocument struct {
	ID          int64              `json:"id"`
	RunID       pgtype.Int8        `json:"run_id"`
	Source      string             `json:"source"`
	SourceUrl   string             `json:"source_url"`
	Method      string             `json:"method"`
	RequestBody string             `json:"request_body"`
	ContentType string             `json:"content_type"`
	FetchedAt   pgtype.Timestamptz `json:"fetched_at"`
	BodyText    string             `json:"body_text"`
	// Optional parsed JSON body for API responses. Not a primary normalized query model.
	BodyJson   []byte `json:"body_json"`
	BodySha256 string `json:"body_sha256"`
	Metadata   []byte `json:"metadata"`
}

// Notice-level rent conversion rules extracted from notice text or attachments.
type RentConversionRule struct {
	ID                   int64       `json:"id"`
	NoticeID             int64       `json:"notice_id"`
	SourceArtifactID     pgtype.Int8 `json:"source_artifact_id"`
	RentToDepositAllowed bool        `json:"rent_to_deposit_allowed"`
	// Maximum monthly rent ratio that can be converted into additional deposit. Example: 0.60.
	RentToDepositMaxRatio pgtype.Numeric `json:"rent_to_deposit_max_ratio"`
	// Annual conversion rate applied when monthly rent is converted to deposit. Example: 0.067.
	RentToDepositAnnualRate pgtype.Numeric `json:"rent_to_deposit_annual_rate"`
	RentUnitKrw             pgtype.Int8    `json:"rent_unit_krw"`
	// Additional deposit required per rent_unit_krw reduction in monthly rent.
	DepositPerRentUnitKrw pgtype.Int8        `json:"deposit_per_rent_unit_krw"`
	DepositToRentAllowed  bool               `json:"deposit_to_rent_allowed"`
	ApplicationCycle      string             `json:"application_cycle"`
	ReapplyLimit          string             `json:"reapply_limit"`
	ApplicationMethod     string             `json:"application_method"`
	SourceText            string             `json:"source_text"`
	SourceSpan            string             `json:"source_span"`
	Confidence            pgtype.Numeric     `json:"confidence"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

// Agency board registry. SH rental and sale boards are separate board_kind values.
type SourceBoard struct {
	ID int64 `json:"id"`
	// Source agency such as SH or LH.
	Agency string `json:"agency"`
	// Board code such as rental or sale.
	BoardKind string             `json:"board_kind"`
	Name      string             `json:"name"`
	SourceUrl string             `json:"source_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Recruitment-family notices that passed discovery gating.
type SourceNotice struct {
	ID            int64       `json:"id"`
	SourceBoardID pgtype.Int8 `json:"source_board_id"`
	Agency        string      `json:"agency"`
	BoardKind     string      `json:"board_kind"`
	// Source site notice sequence. SH examples are numeric strings.
	Seq string `json:"seq"`
	// Legacy prototype category retained for compatibility.
	Category string `json:"category"`
	// Canonical notice type. HIC persists recruitment-family notices only.
	NoticeType string `json:"notice_type"`
	// Correction, additional recruitment, remaining-unit recruitment, or empty when not applicable.
	NoticeSubtype string             `json:"notice_subtype"`
	Title         string             `json:"title"`
	Department    string             `json:"department"`
	PostedAt      pgtype.Date        `json:"posted_at"`
	ViewCount     int32              `json:"view_count"`
	DetailUrl     string             `json:"detail_url"`
	SourceUrl     string             `json:"source_url"`
	BodyText      string             `json:"body_text"`
	RawDocumentID pgtype.Int8        `json:"raw_document_id"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// ObjectStore records for original attachments and generated artifacts.
type StoredObject struct {
	ID     int64  `json:"id"`
	Bucket string `json:"bucket"`
	// Portable logical object key independent of local path or MinIO bucket layout.
	ObjectKey string `json:"object_key"`
	// Logical backend name such as local_filesystem or s3_compatible. Domain logic must depend on ObjectStore, not this implementation detail.
	StorageBackend   string `json:"storage_backend"`
	ContentType      string `json:"content_type"`
	OriginalFilename string `json:"original_filename"`
	// Checksum used for integrity checks and deduplication.
	Sha256    string             `json:"sha256"`
	SizeBytes int64              `json:"size_bytes"`
	StoredAt  pgtype.Timestamptz `json:"stored_at"`
	Metadata  []byte             `json:"metadata"`
}
