// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: poc.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExtractedArtifacts = `-- name: CountExtractedArtifacts :one
select count(*) from extracted_artifacts
`

func (q *Queries) CountExtractedArtifacts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countExtractedArtifacts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOfferings = `-- name: CountOfferings :one
select count(*) from offerings
`

func (q *Queries) CountOfferings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOfferings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOfferingsByQAStatus = `-- name: CountOfferingsByQAStatus :one
select count(*) from offerings
where qa_status = $1
`

func (q *Queries) CountOfferingsByQAStatus(ctx context.Context, qaStatus string) (int64, error) {
	row := q.db.QueryRow(ctx, countOfferingsByQAStatus, qaStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStoredObjects = `-- name: CountStoredObjects :one
select count(*) from stored_objects
`

func (q *Queries) CountStoredObjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStoredObjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollectionRun = `-- name: CreateCollectionRun :one
insert into collection_runs (source, status, stats)
values ($1, 'running', '{}'::jsonb)
returning id
`

func (q *Queries) CreateCollectionRun(ctx context.Context, source string) (int64, error) {
	row := q.db.QueryRow(ctx, createCollectionRun, source)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const finishCollectionRun = `-- name: FinishCollectionRun :exec
update collection_runs
set
	status = $2,
	finished_at = now(),
	stats = $3,
	error_text = $4
where id = $1
`

type FinishCollectionRunParams struct {
	ID        int64       `json:"id"`
	Status    string      `json:"status"`
	Stats     []byte      `json:"stats"`
	ErrorText pgtype.Text `json:"error_text"`
}

func (q *Queries) FinishCollectionRun(ctx context.Context, arg FinishCollectionRunParams) error {
	_, err := q.db.Exec(ctx, finishCollectionRun,
		arg.ID,
		arg.Status,
		arg.Stats,
		arg.ErrorText,
	)
	return err
}

const insertExtractedArtifact = `-- name: InsertExtractedArtifact :one
insert into extracted_artifacts (
	attachment_id,
	stored_object_id,
	artifact_type,
	extractor,
	status,
	schema_version,
	sheet_name,
	page_no,
	row_no,
	cell_ref,
	raw_text,
	content_json,
	source_span,
	confidence,
	error_text
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
on conflict (attachment_id, artifact_type, source_span)
do update set
	stored_object_id = excluded.stored_object_id,
	extractor = excluded.extractor,
	status = excluded.status,
	schema_version = excluded.schema_version,
	sheet_name = excluded.sheet_name,
	page_no = excluded.page_no,
	row_no = excluded.row_no,
	cell_ref = excluded.cell_ref,
	raw_text = excluded.raw_text,
	content_json = excluded.content_json,
	confidence = excluded.confidence,
	error_text = excluded.error_text
returning id
`

type InsertExtractedArtifactParams struct {
	AttachmentID   pgtype.Int8    `json:"attachment_id"`
	StoredObjectID pgtype.Int8    `json:"stored_object_id"`
	ArtifactType   string         `json:"artifact_type"`
	Extractor      string         `json:"extractor"`
	Status         string         `json:"status"`
	SchemaVersion  string         `json:"schema_version"`
	SheetName      string         `json:"sheet_name"`
	PageNo         pgtype.Int4    `json:"page_no"`
	RowNo          pgtype.Int4    `json:"row_no"`
	CellRef        string         `json:"cell_ref"`
	RawText        string         `json:"raw_text"`
	ContentJson    []byte         `json:"content_json"`
	SourceSpan     string         `json:"source_span"`
	Confidence     pgtype.Numeric `json:"confidence"`
	ErrorText      string         `json:"error_text"`
}

func (q *Queries) InsertExtractedArtifact(ctx context.Context, arg InsertExtractedArtifactParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertExtractedArtifact,
		arg.AttachmentID,
		arg.StoredObjectID,
		arg.ArtifactType,
		arg.Extractor,
		arg.Status,
		arg.SchemaVersion,
		arg.SheetName,
		arg.PageNo,
		arg.RowNo,
		arg.CellRef,
		arg.RawText,
		arg.ContentJson,
		arg.SourceSpan,
		arg.Confidence,
		arg.ErrorText,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listExistingNoticeSeqs = `-- name: ListExistingNoticeSeqs :many
select seq
from source_notices
where agency = $1
	and board_kind = $2
	and category = 'recruitment'
`

type ListExistingNoticeSeqsParams struct {
	Agency    string `json:"agency"`
	BoardKind string `json:"board_kind"`
}

func (q *Queries) ListExistingNoticeSeqs(ctx context.Context, arg ListExistingNoticeSeqsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listExistingNoticeSeqs, arg.Agency, arg.BoardKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var seq string
		if err := rows.Scan(&seq); err != nil {
			return nil, err
		}
		items = append(items, seq)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfferings = `-- name: ListOfferings :many
select
	id,
	agency,
	source,
	application_unit_label,
	supply_method,
	application_category,
	supply_category,
	list_no,
	district,
	address,
	housing_name,
	complex_name,
	building_name,
	unit_no,
	unit_type,
	exclusive_area_m2,
	deposit_text,
	deposit_krw,
	jeonse_deposit_text,
	jeonse_deposit_krw,
	contract_deposit_krw,
	balance_payment_krw,
	monthly_rent_text,
	monthly_rent_krw,
	supply_count,
	reserved_count,
	gender_requirement,
	occupancy_type,
	capacity_persons,
	dormitory_fee_krw,
	heating_method,
	move_in_start_text,
	source_sheet,
	source_row,
	source_span,
	qa_status
from offerings
where qa_status = $2
order by id desc
limit $1
`

type ListOfferingsParams struct {
	Limit    int32  `json:"limit"`
	QaStatus string `json:"qa_status"`
}

type ListOfferingsRow struct {
	ID                   int64          `json:"id"`
	Agency               string         `json:"agency"`
	Source               string         `json:"source"`
	ApplicationUnitLabel string         `json:"application_unit_label"`
	SupplyMethod         string         `json:"supply_method"`
	ApplicationCategory  string         `json:"application_category"`
	SupplyCategory       string         `json:"supply_category"`
	ListNo               string         `json:"list_no"`
	District             string         `json:"district"`
	Address              string         `json:"address"`
	HousingName          string         `json:"housing_name"`
	ComplexName          string         `json:"complex_name"`
	BuildingName         string         `json:"building_name"`
	UnitNo               pgtype.Text    `json:"unit_no"`
	UnitType             string         `json:"unit_type"`
	ExclusiveAreaM2      pgtype.Numeric `json:"exclusive_area_m2"`
	DepositText          string         `json:"deposit_text"`
	DepositKrw           pgtype.Int8    `json:"deposit_krw"`
	JeonseDepositText    string         `json:"jeonse_deposit_text"`
	JeonseDepositKrw     pgtype.Int8    `json:"jeonse_deposit_krw"`
	ContractDepositKrw   pgtype.Int8    `json:"contract_deposit_krw"`
	BalancePaymentKrw    pgtype.Int8    `json:"balance_payment_krw"`
	MonthlyRentText      string         `json:"monthly_rent_text"`
	MonthlyRentKrw       pgtype.Int8    `json:"monthly_rent_krw"`
	SupplyCount          pgtype.Int4    `json:"supply_count"`
	ReservedCount        pgtype.Int4    `json:"reserved_count"`
	GenderRequirement    string         `json:"gender_requirement"`
	OccupancyType        string         `json:"occupancy_type"`
	CapacityPersons      pgtype.Int4    `json:"capacity_persons"`
	DormitoryFeeKrw      pgtype.Int8    `json:"dormitory_fee_krw"`
	HeatingMethod        string         `json:"heating_method"`
	MoveInStartText      string         `json:"move_in_start_text"`
	SourceSheet          string         `json:"source_sheet"`
	SourceRow            pgtype.Int4    `json:"source_row"`
	SourceSpan           string         `json:"source_span"`
	QaStatus             string         `json:"qa_status"`
}

func (q *Queries) ListOfferings(ctx context.Context, arg ListOfferingsParams) ([]ListOfferingsRow, error) {
	rows, err := q.db.Query(ctx, listOfferings, arg.Limit, arg.QaStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOfferingsRow
	for rows.Next() {
		var i ListOfferingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Agency,
			&i.Source,
			&i.ApplicationUnitLabel,
			&i.SupplyMethod,
			&i.ApplicationCategory,
			&i.SupplyCategory,
			&i.ListNo,
			&i.District,
			&i.Address,
			&i.HousingName,
			&i.ComplexName,
			&i.BuildingName,
			&i.UnitNo,
			&i.UnitType,
			&i.ExclusiveAreaM2,
			&i.DepositText,
			&i.DepositKrw,
			&i.JeonseDepositText,
			&i.JeonseDepositKrw,
			&i.ContractDepositKrw,
			&i.BalancePaymentKrw,
			&i.MonthlyRentText,
			&i.MonthlyRentKrw,
			&i.SupplyCount,
			&i.ReservedCount,
			&i.GenderRequirement,
			&i.OccupancyType,
			&i.CapacityPersons,
			&i.DormitoryFeeKrw,
			&i.HeatingMethod,
			&i.MoveInStartText,
			&i.SourceSheet,
			&i.SourceRow,
			&i.SourceSpan,
			&i.QaStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceNotices = `-- name: ListSourceNotices :many
select
	id,
	agency,
	board_kind,
	seq,
	notice_type,
	title,
	posted_at,
	source_url
from source_notices
where category = 'recruitment'
	and not (
		title like '%당첨자%'
		or title like '%서류심사대상자%'
		or title like '%동호배정%'
		or title like '%결과%'
		or title like '%계약%'
		or title like '%청약경쟁률%'
		or title like '%경쟁률%'
		or title like '%청약접수%'
		or title like '%접수결과%'
		or title like '%접수 결과%'
		or title like '%접수마감%'
		or title like '%시스템%'
		or title like '%서비스 일시중단%'
	)
order by posted_at desc nulls last, id desc
limit $1
`

type ListSourceNoticesRow struct {
	ID         int64       `json:"id"`
	Agency     string      `json:"agency"`
	BoardKind  string      `json:"board_kind"`
	Seq        string      `json:"seq"`
	NoticeType string      `json:"notice_type"`
	Title      string      `json:"title"`
	PostedAt   pgtype.Date `json:"posted_at"`
	SourceUrl  string      `json:"source_url"`
}

func (q *Queries) ListSourceNotices(ctx context.Context, limit int32) ([]ListSourceNoticesRow, error) {
	rows, err := q.db.Query(ctx, listSourceNotices, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceNoticesRow
	for rows.Next() {
		var i ListSourceNoticesRow
		if err := rows.Scan(
			&i.ID,
			&i.Agency,
			&i.BoardKind,
			&i.Seq,
			&i.NoticeType,
			&i.Title,
			&i.PostedAt,
			&i.SourceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteOfferingsQA = `-- name: PromoteOfferingsQA :exec
update offerings
set qa_status = case
	when exists (
			select 1
			from source_notices sn
			where sn.id = offerings.notice_id
				and sn.category = 'recruitment'
		)
		and notice_id is not null
		and attachment_id is not null
		and source_artifact_id is not null
		and trim(source_span) <> ''
		and (
			trim(application_unit_label) <> ''
			or coalesce(trim(unit_no), '') <> ''
			or trim(coalesce(nullif(housing_name, ''), complex_name)) <> ''
		)
		and (
			coalesce(trim(unit_no), '') <> ''
			or (
				supply_count is not null
				and supply_count > 0
			)
		)
		and (
			(
				exclusive_area_m2 is not null
				and exclusive_area_m2 > 0
			)
			or trim(occupancy_type) <> ''
		)
		and (
			(
				deposit_krw is not null
				and deposit_krw >= 0
				and monthly_rent_krw is not null
				and monthly_rent_krw >= 0
			)
			or (
				jeonse_deposit_krw is not null
				and jeonse_deposit_krw >= 0
			)
			or (
				dormitory_fee_krw is not null
				and dormitory_fee_krw >= 0
			)
		)
	then 'approved'
	else 'rejected'
end
where qa_status = 'pending'
`

func (q *Queries) PromoteOfferingsQA(ctx context.Context) error {
	_, err := q.db.Exec(ctx, promoteOfferingsQA)
	return err
}

const upsertAttachment = `-- name: UpsertAttachment :one
insert into attachments (
	notice_id,
	stored_object_id,
	brd_id,
	seq,
	file_seq,
	original_filename,
	file_ext,
	file_size,
	content_type,
	object_key,
	sha256,
	attachment_kind,
	extractor_status,
	raw_metadata
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
on conflict (brd_id, seq, file_seq)
do update set
	notice_id = excluded.notice_id,
	stored_object_id = excluded.stored_object_id,
	original_filename = excluded.original_filename,
	file_ext = excluded.file_ext,
	file_size = excluded.file_size,
	content_type = excluded.content_type,
	object_key = excluded.object_key,
	sha256 = excluded.sha256,
	attachment_kind = excluded.attachment_kind,
	extractor_status = excluded.extractor_status,
	raw_metadata = excluded.raw_metadata
returning id
`

type UpsertAttachmentParams struct {
	NoticeID         pgtype.Int8 `json:"notice_id"`
	StoredObjectID   pgtype.Int8 `json:"stored_object_id"`
	BrdID            string      `json:"brd_id"`
	Seq              string      `json:"seq"`
	FileSeq          string      `json:"file_seq"`
	OriginalFilename string      `json:"original_filename"`
	FileExt          string      `json:"file_ext"`
	FileSize         int64       `json:"file_size"`
	ContentType      string      `json:"content_type"`
	ObjectKey        string      `json:"object_key"`
	Sha256           string      `json:"sha256"`
	AttachmentKind   string      `json:"attachment_kind"`
	ExtractorStatus  string      `json:"extractor_status"`
	RawMetadata      []byte      `json:"raw_metadata"`
}

func (q *Queries) UpsertAttachment(ctx context.Context, arg UpsertAttachmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertAttachment,
		arg.NoticeID,
		arg.StoredObjectID,
		arg.BrdID,
		arg.Seq,
		arg.FileSeq,
		arg.OriginalFilename,
		arg.FileExt,
		arg.FileSize,
		arg.ContentType,
		arg.ObjectKey,
		arg.Sha256,
		arg.AttachmentKind,
		arg.ExtractorStatus,
		arg.RawMetadata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertOffering = `-- name: UpsertOffering :one
insert into offerings (
	notice_id,
	attachment_id,
	source_artifact_id,
	agency,
	source,
	application_unit_label,
	supply_method,
	application_category,
	supply_category,
	list_no,
	district,
	address,
	legal_dong,
	address_detail,
	housing_name,
	complex_name,
	building_name,
	unit_no,
	floor,
	floor_no,
	unit_type,
	structure_type,
	exclusive_area_m2,
	area_pyeong,
	deposit_text,
	deposit_krw,
	jeonse_deposit_text,
	jeonse_deposit_krw,
	contract_deposit_krw,
	balance_payment_krw,
	monthly_rent_text,
	monthly_rent_krw,
	supply_count,
	reserved_count,
	gender_requirement,
	occupancy_type,
	capacity_persons,
	dormitory_fee_krw,
	heating_method,
	move_in_start_text,
	direction,
	status,
	source_sheet,
	source_row,
	source_cell,
	source_page,
	source_span,
	raw_row,
	confidence,
	qa_status
)
values (
	$1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
	$11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
	$21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
	$31, $32, $33, $34, $35, $36, $37, $38, $39, $40,
	$41, $42, $43, $44, $45, $46, $47, $48, $49, $50
)
on conflict (attachment_id, source_span)
where source_span <> ''
do update set
	source_artifact_id = excluded.source_artifact_id,
	agency = excluded.agency,
	source = excluded.source,
	application_unit_label = excluded.application_unit_label,
	supply_method = excluded.supply_method,
	application_category = excluded.application_category,
	supply_category = excluded.supply_category,
	list_no = excluded.list_no,
	district = excluded.district,
	address = excluded.address,
	legal_dong = excluded.legal_dong,
	address_detail = excluded.address_detail,
	housing_name = excluded.housing_name,
	complex_name = excluded.complex_name,
	building_name = excluded.building_name,
	unit_no = excluded.unit_no,
	floor = excluded.floor,
	floor_no = excluded.floor_no,
	unit_type = excluded.unit_type,
	structure_type = excluded.structure_type,
	exclusive_area_m2 = excluded.exclusive_area_m2,
	area_pyeong = excluded.area_pyeong,
	deposit_text = excluded.deposit_text,
	deposit_krw = excluded.deposit_krw,
	jeonse_deposit_text = excluded.jeonse_deposit_text,
	jeonse_deposit_krw = excluded.jeonse_deposit_krw,
	contract_deposit_krw = excluded.contract_deposit_krw,
	balance_payment_krw = excluded.balance_payment_krw,
	monthly_rent_text = excluded.monthly_rent_text,
	monthly_rent_krw = excluded.monthly_rent_krw,
	supply_count = excluded.supply_count,
	reserved_count = excluded.reserved_count,
	gender_requirement = excluded.gender_requirement,
	occupancy_type = excluded.occupancy_type,
	capacity_persons = excluded.capacity_persons,
	dormitory_fee_krw = excluded.dormitory_fee_krw,
	heating_method = excluded.heating_method,
	move_in_start_text = excluded.move_in_start_text,
	direction = excluded.direction,
	status = excluded.status,
	source_sheet = excluded.source_sheet,
	source_row = excluded.source_row,
	source_cell = excluded.source_cell,
	source_page = excluded.source_page,
	raw_row = excluded.raw_row,
	confidence = excluded.confidence,
	qa_status = case when offerings.qa_status = 'approved' then 'approved' else excluded.qa_status end
returning id
`

type UpsertOfferingParams struct {
	NoticeID             pgtype.Int8    `json:"notice_id"`
	AttachmentID         pgtype.Int8    `json:"attachment_id"`
	SourceArtifactID     pgtype.Int8    `json:"source_artifact_id"`
	Agency               string         `json:"agency"`
	Source               string         `json:"source"`
	ApplicationUnitLabel string         `json:"application_unit_label"`
	SupplyMethod         string         `json:"supply_method"`
	ApplicationCategory  string         `json:"application_category"`
	SupplyCategory       string         `json:"supply_category"`
	ListNo               string         `json:"list_no"`
	District             string         `json:"district"`
	Address              string         `json:"address"`
	LegalDong            string         `json:"legal_dong"`
	AddressDetail        string         `json:"address_detail"`
	HousingName          string         `json:"housing_name"`
	ComplexName          string         `json:"complex_name"`
	BuildingName         string         `json:"building_name"`
	UnitNo               pgtype.Text    `json:"unit_no"`
	Floor                pgtype.Int4    `json:"floor"`
	FloorNo              pgtype.Int4    `json:"floor_no"`
	UnitType             string         `json:"unit_type"`
	StructureType        string         `json:"structure_type"`
	ExclusiveAreaM2      pgtype.Numeric `json:"exclusive_area_m2"`
	AreaPyeong           pgtype.Numeric `json:"area_pyeong"`
	DepositText          string         `json:"deposit_text"`
	DepositKrw           pgtype.Int8    `json:"deposit_krw"`
	JeonseDepositText    string         `json:"jeonse_deposit_text"`
	JeonseDepositKrw     pgtype.Int8    `json:"jeonse_deposit_krw"`
	ContractDepositKrw   pgtype.Int8    `json:"contract_deposit_krw"`
	BalancePaymentKrw    pgtype.Int8    `json:"balance_payment_krw"`
	MonthlyRentText      string         `json:"monthly_rent_text"`
	MonthlyRentKrw       pgtype.Int8    `json:"monthly_rent_krw"`
	SupplyCount          pgtype.Int4    `json:"supply_count"`
	ReservedCount        pgtype.Int4    `json:"reserved_count"`
	GenderRequirement    string         `json:"gender_requirement"`
	OccupancyType        string         `json:"occupancy_type"`
	CapacityPersons      pgtype.Int4    `json:"capacity_persons"`
	DormitoryFeeKrw      pgtype.Int8    `json:"dormitory_fee_krw"`
	HeatingMethod        string         `json:"heating_method"`
	MoveInStartText      string         `json:"move_in_start_text"`
	Direction            string         `json:"direction"`
	Status               string         `json:"status"`
	SourceSheet          string         `json:"source_sheet"`
	SourceRow            pgtype.Int4    `json:"source_row"`
	SourceCell           string         `json:"source_cell"`
	SourcePage           pgtype.Int4    `json:"source_page"`
	SourceSpan           string         `json:"source_span"`
	RawRow               []byte         `json:"raw_row"`
	Confidence           pgtype.Numeric `json:"confidence"`
	QaStatus             string         `json:"qa_status"`
}

func (q *Queries) UpsertOffering(ctx context.Context, arg UpsertOfferingParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertOffering,
		arg.NoticeID,
		arg.AttachmentID,
		arg.SourceArtifactID,
		arg.Agency,
		arg.Source,
		arg.ApplicationUnitLabel,
		arg.SupplyMethod,
		arg.ApplicationCategory,
		arg.SupplyCategory,
		arg.ListNo,
		arg.District,
		arg.Address,
		arg.LegalDong,
		arg.AddressDetail,
		arg.HousingName,
		arg.ComplexName,
		arg.BuildingName,
		arg.UnitNo,
		arg.Floor,
		arg.FloorNo,
		arg.UnitType,
		arg.StructureType,
		arg.ExclusiveAreaM2,
		arg.AreaPyeong,
		arg.DepositText,
		arg.DepositKrw,
		arg.JeonseDepositText,
		arg.JeonseDepositKrw,
		arg.ContractDepositKrw,
		arg.BalancePaymentKrw,
		arg.MonthlyRentText,
		arg.MonthlyRentKrw,
		arg.SupplyCount,
		arg.ReservedCount,
		arg.GenderRequirement,
		arg.OccupancyType,
		arg.CapacityPersons,
		arg.DormitoryFeeKrw,
		arg.HeatingMethod,
		arg.MoveInStartText,
		arg.Direction,
		arg.Status,
		arg.SourceSheet,
		arg.SourceRow,
		arg.SourceCell,
		arg.SourcePage,
		arg.SourceSpan,
		arg.RawRow,
		arg.Confidence,
		arg.QaStatus,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertSourceBoard = `-- name: UpsertSourceBoard :one
insert into source_boards (agency, board_kind, name, source_url)
values ($1, $2, $3, $4)
on conflict (agency, board_kind)
do update set
	name = excluded.name,
	source_url = excluded.source_url,
	updated_at = now()
returning id
`

type UpsertSourceBoardParams struct {
	Agency    string `json:"agency"`
	BoardKind string `json:"board_kind"`
	Name      string `json:"name"`
	SourceUrl string `json:"source_url"`
}

func (q *Queries) UpsertSourceBoard(ctx context.Context, arg UpsertSourceBoardParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSourceBoard,
		arg.Agency,
		arg.BoardKind,
		arg.Name,
		arg.SourceUrl,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertSourceNotice = `-- name: UpsertSourceNotice :one
insert into source_notices (
	source_board_id,
	agency,
	board_kind,
	seq,
	category,
	notice_type,
	notice_subtype,
	title,
	posted_at,
	source_url,
	body_text
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
on conflict (agency, board_kind, seq)
do update set
	source_board_id = excluded.source_board_id,
	category = excluded.category,
	notice_type = excluded.notice_type,
	notice_subtype = excluded.notice_subtype,
	title = excluded.title,
	posted_at = excluded.posted_at,
	source_url = excluded.source_url,
	body_text = excluded.body_text,
	updated_at = now()
returning id
`

type UpsertSourceNoticeParams struct {
	SourceBoardID pgtype.Int8 `json:"source_board_id"`
	Agency        string      `json:"agency"`
	BoardKind     string      `json:"board_kind"`
	Seq           string      `json:"seq"`
	Category      string      `json:"category"`
	NoticeType    string      `json:"notice_type"`
	NoticeSubtype string      `json:"notice_subtype"`
	Title         string      `json:"title"`
	PostedAt      pgtype.Date `json:"posted_at"`
	SourceUrl     string      `json:"source_url"`
	BodyText      string      `json:"body_text"`
}

func (q *Queries) UpsertSourceNotice(ctx context.Context, arg UpsertSourceNoticeParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSourceNotice,
		arg.SourceBoardID,
		arg.Agency,
		arg.BoardKind,
		arg.Seq,
		arg.Category,
		arg.NoticeType,
		arg.NoticeSubtype,
		arg.Title,
		arg.PostedAt,
		arg.SourceUrl,
		arg.BodyText,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertStoredObject = `-- name: UpsertStoredObject :one
insert into stored_objects (
	bucket,
	object_key,
	storage_backend,
	content_type,
	original_filename,
	sha256,
	size_bytes,
	metadata
)
values ($1, $2, $3, $4, $5, $6, $7, $8)
on conflict (bucket, object_key)
do update set
	storage_backend = excluded.storage_backend,
	content_type = excluded.content_type,
	original_filename = excluded.original_filename,
	sha256 = excluded.sha256,
	size_bytes = excluded.size_bytes,
	metadata = excluded.metadata
returning id
`

type UpsertStoredObjectParams struct {
	Bucket           string `json:"bucket"`
	ObjectKey        string `json:"object_key"`
	StorageBackend   string `json:"storage_backend"`
	ContentType      string `json:"content_type"`
	OriginalFilename string `json:"original_filename"`
	Sha256           string `json:"sha256"`
	SizeBytes        int64  `json:"size_bytes"`
	Metadata         []byte `json:"metadata"`
}

func (q *Queries) UpsertStoredObject(ctx context.Context, arg UpsertStoredObjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertStoredObject,
		arg.Bucket,
		arg.ObjectKey,
		arg.StorageBackend,
		arg.ContentType,
		arg.OriginalFilename,
		arg.Sha256,
		arg.SizeBytes,
		arg.Metadata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
