// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: poc.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExtractedArtifacts = `-- name: CountExtractedArtifacts :one
select count(*) from extracted_artifacts
`

func (q *Queries) CountExtractedArtifacts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countExtractedArtifacts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHousingUnits = `-- name: CountHousingUnits :one
select count(*) from housing_units
`

func (q *Queries) CountHousingUnits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countHousingUnits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStoredObjects = `-- name: CountStoredObjects :one
select count(*) from stored_objects
`

func (q *Queries) CountStoredObjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStoredObjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertExtractedArtifact = `-- name: InsertExtractedArtifact :one
insert into extracted_artifacts (
	attachment_id,
	stored_object_id,
	artifact_type,
	extractor,
	status,
	schema_version,
	sheet_name,
	page_no,
	row_no,
	cell_ref,
	raw_text,
	content_json,
	source_span,
	confidence,
	error_text
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
on conflict (attachment_id, artifact_type, source_span)
do update set
	stored_object_id = excluded.stored_object_id,
	extractor = excluded.extractor,
	status = excluded.status,
	schema_version = excluded.schema_version,
	sheet_name = excluded.sheet_name,
	page_no = excluded.page_no,
	row_no = excluded.row_no,
	cell_ref = excluded.cell_ref,
	raw_text = excluded.raw_text,
	content_json = excluded.content_json,
	confidence = excluded.confidence,
	error_text = excluded.error_text
returning id
`

type InsertExtractedArtifactParams struct {
	AttachmentID   pgtype.Int8    `json:"attachment_id"`
	StoredObjectID pgtype.Int8    `json:"stored_object_id"`
	ArtifactType   string         `json:"artifact_type"`
	Extractor      string         `json:"extractor"`
	Status         string         `json:"status"`
	SchemaVersion  string         `json:"schema_version"`
	SheetName      string         `json:"sheet_name"`
	PageNo         pgtype.Int4    `json:"page_no"`
	RowNo          pgtype.Int4    `json:"row_no"`
	CellRef        string         `json:"cell_ref"`
	RawText        string         `json:"raw_text"`
	ContentJson    []byte         `json:"content_json"`
	SourceSpan     string         `json:"source_span"`
	Confidence     pgtype.Numeric `json:"confidence"`
	ErrorText      string         `json:"error_text"`
}

func (q *Queries) InsertExtractedArtifact(ctx context.Context, arg InsertExtractedArtifactParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertExtractedArtifact,
		arg.AttachmentID,
		arg.StoredObjectID,
		arg.ArtifactType,
		arg.Extractor,
		arg.Status,
		arg.SchemaVersion,
		arg.SheetName,
		arg.PageNo,
		arg.RowNo,
		arg.CellRef,
		arg.RawText,
		arg.ContentJson,
		arg.SourceSpan,
		arg.Confidence,
		arg.ErrorText,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listExistingNoticeSeqs = `-- name: ListExistingNoticeSeqs :many
select seq
from source_notices
where agency = $1
	and board_kind = $2
	and category = 'recruitment'
`

type ListExistingNoticeSeqsParams struct {
	Agency    string `json:"agency"`
	BoardKind string `json:"board_kind"`
}

func (q *Queries) ListExistingNoticeSeqs(ctx context.Context, arg ListExistingNoticeSeqsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listExistingNoticeSeqs, arg.Agency, arg.BoardKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var seq string
		if err := rows.Scan(&seq); err != nil {
			return nil, err
		}
		items = append(items, seq)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHousingUnits = `-- name: ListHousingUnits :many
select
	id,
	agency,
	source,
	supply_category,
	list_no,
	district,
	address,
	housing_name,
	complex_name,
	building_name,
	unit_no,
	unit_type,
	exclusive_area_m2,
	deposit_text,
	deposit_krw,
	monthly_rent_text,
	monthly_rent_krw,
	source_sheet,
	source_row,
	source_span,
	qa_status
from housing_units
order by id desc
limit $1
`

type ListHousingUnitsRow struct {
	ID              int64          `json:"id"`
	Agency          string         `json:"agency"`
	Source          string         `json:"source"`
	SupplyCategory  string         `json:"supply_category"`
	ListNo          string         `json:"list_no"`
	District        string         `json:"district"`
	Address         string         `json:"address"`
	HousingName     string         `json:"housing_name"`
	ComplexName     string         `json:"complex_name"`
	BuildingName    string         `json:"building_name"`
	UnitNo          string         `json:"unit_no"`
	UnitType        string         `json:"unit_type"`
	ExclusiveAreaM2 pgtype.Numeric `json:"exclusive_area_m2"`
	DepositText     string         `json:"deposit_text"`
	DepositKrw      pgtype.Int8    `json:"deposit_krw"`
	MonthlyRentText string         `json:"monthly_rent_text"`
	MonthlyRentKrw  pgtype.Int8    `json:"monthly_rent_krw"`
	SourceSheet     string         `json:"source_sheet"`
	SourceRow       pgtype.Int4    `json:"source_row"`
	SourceSpan      string         `json:"source_span"`
	QaStatus        string         `json:"qa_status"`
}

func (q *Queries) ListHousingUnits(ctx context.Context, limit int32) ([]ListHousingUnitsRow, error) {
	rows, err := q.db.Query(ctx, listHousingUnits, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHousingUnitsRow
	for rows.Next() {
		var i ListHousingUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Agency,
			&i.Source,
			&i.SupplyCategory,
			&i.ListNo,
			&i.District,
			&i.Address,
			&i.HousingName,
			&i.ComplexName,
			&i.BuildingName,
			&i.UnitNo,
			&i.UnitType,
			&i.ExclusiveAreaM2,
			&i.DepositText,
			&i.DepositKrw,
			&i.MonthlyRentText,
			&i.MonthlyRentKrw,
			&i.SourceSheet,
			&i.SourceRow,
			&i.SourceSpan,
			&i.QaStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceNotices = `-- name: ListSourceNotices :many
select
	id,
	agency,
	board_kind,
	seq,
	notice_type,
	title,
	posted_at,
	source_url
from source_notices
where category = 'recruitment'
	and not (
		title like '%당첨자%'
		or title like '%서류심사대상자%'
		or title like '%동호배정%'
		or title like '%결과%'
		or title like '%계약%'
		or title like '%청약경쟁률%'
		or title like '%경쟁률%'
		or title like '%청약접수%'
		or title like '%접수결과%'
		or title like '%접수 결과%'
		or title like '%접수마감%'
		or title like '%시스템%'
		or title like '%서비스 일시중단%'
	)
order by posted_at desc nulls last, id desc
limit $1
`

type ListSourceNoticesRow struct {
	ID         int64       `json:"id"`
	Agency     string      `json:"agency"`
	BoardKind  string      `json:"board_kind"`
	Seq        string      `json:"seq"`
	NoticeType string      `json:"notice_type"`
	Title      string      `json:"title"`
	PostedAt   pgtype.Date `json:"posted_at"`
	SourceUrl  string      `json:"source_url"`
}

func (q *Queries) ListSourceNotices(ctx context.Context, limit int32) ([]ListSourceNoticesRow, error) {
	rows, err := q.db.Query(ctx, listSourceNotices, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceNoticesRow
	for rows.Next() {
		var i ListSourceNoticesRow
		if err := rows.Scan(
			&i.ID,
			&i.Agency,
			&i.BoardKind,
			&i.Seq,
			&i.NoticeType,
			&i.Title,
			&i.PostedAt,
			&i.SourceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttachment = `-- name: UpsertAttachment :one
insert into attachments (
	notice_id,
	stored_object_id,
	brd_id,
	seq,
	file_seq,
	original_filename,
	file_ext,
	file_size,
	content_type,
	object_key,
	sha256,
	attachment_kind,
	extractor_status,
	raw_metadata
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
on conflict (brd_id, seq, file_seq)
do update set
	notice_id = excluded.notice_id,
	stored_object_id = excluded.stored_object_id,
	original_filename = excluded.original_filename,
	file_ext = excluded.file_ext,
	file_size = excluded.file_size,
	content_type = excluded.content_type,
	object_key = excluded.object_key,
	sha256 = excluded.sha256,
	attachment_kind = excluded.attachment_kind,
	extractor_status = excluded.extractor_status,
	raw_metadata = excluded.raw_metadata
returning id
`

type UpsertAttachmentParams struct {
	NoticeID         pgtype.Int8 `json:"notice_id"`
	StoredObjectID   pgtype.Int8 `json:"stored_object_id"`
	BrdID            string      `json:"brd_id"`
	Seq              string      `json:"seq"`
	FileSeq          string      `json:"file_seq"`
	OriginalFilename string      `json:"original_filename"`
	FileExt          string      `json:"file_ext"`
	FileSize         int64       `json:"file_size"`
	ContentType      string      `json:"content_type"`
	ObjectKey        string      `json:"object_key"`
	Sha256           string      `json:"sha256"`
	AttachmentKind   string      `json:"attachment_kind"`
	ExtractorStatus  string      `json:"extractor_status"`
	RawMetadata      []byte      `json:"raw_metadata"`
}

func (q *Queries) UpsertAttachment(ctx context.Context, arg UpsertAttachmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertAttachment,
		arg.NoticeID,
		arg.StoredObjectID,
		arg.BrdID,
		arg.Seq,
		arg.FileSeq,
		arg.OriginalFilename,
		arg.FileExt,
		arg.FileSize,
		arg.ContentType,
		arg.ObjectKey,
		arg.Sha256,
		arg.AttachmentKind,
		arg.ExtractorStatus,
		arg.RawMetadata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertHousingUnit = `-- name: UpsertHousingUnit :one
insert into housing_units (
	notice_id,
	attachment_id,
	source_artifact_id,
	agency,
	source,
	supply_category,
	list_no,
	district,
	address,
	legal_dong,
	address_detail,
	housing_name,
	complex_name,
	building_name,
	unit_no,
	floor,
	floor_no,
	unit_type,
	structure_type,
	exclusive_area_m2,
	area_pyeong,
	deposit_text,
	deposit_krw,
	monthly_rent_text,
	monthly_rent_krw,
	supply_count,
	direction,
	status,
	source_sheet,
	source_row,
	source_cell,
	source_page,
	source_span,
	raw_row,
	confidence,
	qa_status
)
values (
	$1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
	$11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
	$21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
	$31, $32, $33, $34, $35, $36
)
on conflict (attachment_id, source_span)
where source_span <> ''
do update set
	source_artifact_id = excluded.source_artifact_id,
	agency = excluded.agency,
	source = excluded.source,
	supply_category = excluded.supply_category,
	list_no = excluded.list_no,
	district = excluded.district,
	address = excluded.address,
	legal_dong = excluded.legal_dong,
	address_detail = excluded.address_detail,
	housing_name = excluded.housing_name,
	complex_name = excluded.complex_name,
	building_name = excluded.building_name,
	unit_no = excluded.unit_no,
	floor = excluded.floor,
	floor_no = excluded.floor_no,
	unit_type = excluded.unit_type,
	structure_type = excluded.structure_type,
	exclusive_area_m2 = excluded.exclusive_area_m2,
	area_pyeong = excluded.area_pyeong,
	deposit_text = excluded.deposit_text,
	deposit_krw = excluded.deposit_krw,
	monthly_rent_text = excluded.monthly_rent_text,
	monthly_rent_krw = excluded.monthly_rent_krw,
	supply_count = excluded.supply_count,
	direction = excluded.direction,
	status = excluded.status,
	source_sheet = excluded.source_sheet,
	source_row = excluded.source_row,
	source_cell = excluded.source_cell,
	source_page = excluded.source_page,
	raw_row = excluded.raw_row,
	confidence = excluded.confidence,
	qa_status = excluded.qa_status
returning id
`

type UpsertHousingUnitParams struct {
	NoticeID         pgtype.Int8    `json:"notice_id"`
	AttachmentID     pgtype.Int8    `json:"attachment_id"`
	SourceArtifactID pgtype.Int8    `json:"source_artifact_id"`
	Agency           string         `json:"agency"`
	Source           string         `json:"source"`
	SupplyCategory   string         `json:"supply_category"`
	ListNo           string         `json:"list_no"`
	District         string         `json:"district"`
	Address          string         `json:"address"`
	LegalDong        string         `json:"legal_dong"`
	AddressDetail    string         `json:"address_detail"`
	HousingName      string         `json:"housing_name"`
	ComplexName      string         `json:"complex_name"`
	BuildingName     string         `json:"building_name"`
	UnitNo           string         `json:"unit_no"`
	Floor            pgtype.Int4    `json:"floor"`
	FloorNo          pgtype.Int4    `json:"floor_no"`
	UnitType         string         `json:"unit_type"`
	StructureType    string         `json:"structure_type"`
	ExclusiveAreaM2  pgtype.Numeric `json:"exclusive_area_m2"`
	AreaPyeong       pgtype.Numeric `json:"area_pyeong"`
	DepositText      string         `json:"deposit_text"`
	DepositKrw       pgtype.Int8    `json:"deposit_krw"`
	MonthlyRentText  string         `json:"monthly_rent_text"`
	MonthlyRentKrw   pgtype.Int8    `json:"monthly_rent_krw"`
	SupplyCount      pgtype.Int4    `json:"supply_count"`
	Direction        string         `json:"direction"`
	Status           string         `json:"status"`
	SourceSheet      string         `json:"source_sheet"`
	SourceRow        pgtype.Int4    `json:"source_row"`
	SourceCell       string         `json:"source_cell"`
	SourcePage       pgtype.Int4    `json:"source_page"`
	SourceSpan       string         `json:"source_span"`
	RawRow           []byte         `json:"raw_row"`
	Confidence       pgtype.Numeric `json:"confidence"`
	QaStatus         string         `json:"qa_status"`
}

func (q *Queries) UpsertHousingUnit(ctx context.Context, arg UpsertHousingUnitParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertHousingUnit,
		arg.NoticeID,
		arg.AttachmentID,
		arg.SourceArtifactID,
		arg.Agency,
		arg.Source,
		arg.SupplyCategory,
		arg.ListNo,
		arg.District,
		arg.Address,
		arg.LegalDong,
		arg.AddressDetail,
		arg.HousingName,
		arg.ComplexName,
		arg.BuildingName,
		arg.UnitNo,
		arg.Floor,
		arg.FloorNo,
		arg.UnitType,
		arg.StructureType,
		arg.ExclusiveAreaM2,
		arg.AreaPyeong,
		arg.DepositText,
		arg.DepositKrw,
		arg.MonthlyRentText,
		arg.MonthlyRentKrw,
		arg.SupplyCount,
		arg.Direction,
		arg.Status,
		arg.SourceSheet,
		arg.SourceRow,
		arg.SourceCell,
		arg.SourcePage,
		arg.SourceSpan,
		arg.RawRow,
		arg.Confidence,
		arg.QaStatus,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertSourceBoard = `-- name: UpsertSourceBoard :one
insert into source_boards (agency, board_kind, name, source_url)
values ($1, $2, $3, $4)
on conflict (agency, board_kind)
do update set
	name = excluded.name,
	source_url = excluded.source_url,
	updated_at = now()
returning id
`

type UpsertSourceBoardParams struct {
	Agency    string `json:"agency"`
	BoardKind string `json:"board_kind"`
	Name      string `json:"name"`
	SourceUrl string `json:"source_url"`
}

func (q *Queries) UpsertSourceBoard(ctx context.Context, arg UpsertSourceBoardParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSourceBoard,
		arg.Agency,
		arg.BoardKind,
		arg.Name,
		arg.SourceUrl,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertSourceNotice = `-- name: UpsertSourceNotice :one
insert into source_notices (
	source_board_id,
	agency,
	board_kind,
	seq,
	category,
	notice_type,
	notice_subtype,
	title,
	posted_at,
	source_url,
	body_text
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
on conflict (agency, board_kind, seq)
do update set
	source_board_id = excluded.source_board_id,
	category = excluded.category,
	notice_type = excluded.notice_type,
	notice_subtype = excluded.notice_subtype,
	title = excluded.title,
	posted_at = excluded.posted_at,
	source_url = excluded.source_url,
	body_text = excluded.body_text,
	updated_at = now()
returning id
`

type UpsertSourceNoticeParams struct {
	SourceBoardID pgtype.Int8 `json:"source_board_id"`
	Agency        string      `json:"agency"`
	BoardKind     string      `json:"board_kind"`
	Seq           string      `json:"seq"`
	Category      string      `json:"category"`
	NoticeType    string      `json:"notice_type"`
	NoticeSubtype string      `json:"notice_subtype"`
	Title         string      `json:"title"`
	PostedAt      pgtype.Date `json:"posted_at"`
	SourceUrl     string      `json:"source_url"`
	BodyText      string      `json:"body_text"`
}

func (q *Queries) UpsertSourceNotice(ctx context.Context, arg UpsertSourceNoticeParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSourceNotice,
		arg.SourceBoardID,
		arg.Agency,
		arg.BoardKind,
		arg.Seq,
		arg.Category,
		arg.NoticeType,
		arg.NoticeSubtype,
		arg.Title,
		arg.PostedAt,
		arg.SourceUrl,
		arg.BodyText,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertStoredObject = `-- name: UpsertStoredObject :one
insert into stored_objects (
	bucket,
	object_key,
	storage_backend,
	content_type,
	original_filename,
	sha256,
	size_bytes,
	metadata
)
values ($1, $2, $3, $4, $5, $6, $7, $8)
on conflict (bucket, object_key)
do update set
	storage_backend = excluded.storage_backend,
	content_type = excluded.content_type,
	original_filename = excluded.original_filename,
	sha256 = excluded.sha256,
	size_bytes = excluded.size_bytes,
	metadata = excluded.metadata
returning id
`

type UpsertStoredObjectParams struct {
	Bucket           string `json:"bucket"`
	ObjectKey        string `json:"object_key"`
	StorageBackend   string `json:"storage_backend"`
	ContentType      string `json:"content_type"`
	OriginalFilename string `json:"original_filename"`
	Sha256           string `json:"sha256"`
	SizeBytes        int64  `json:"size_bytes"`
	Metadata         []byte `json:"metadata"`
}

func (q *Queries) UpsertStoredObject(ctx context.Context, arg UpsertStoredObjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertStoredObject,
		arg.Bucket,
		arg.ObjectKey,
		arg.StorageBackend,
		arg.ContentType,
		arg.OriginalFilename,
		arg.Sha256,
		arg.SizeBytes,
		arg.Metadata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
