// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountExtractedArtifacts(ctx context.Context) (int64, error)
	CountHousingUnits(ctx context.Context) (int64, error)
	CountHousingUnitsByQAStatus(ctx context.Context, qaStatus string) (int64, error)
	CountStoredObjects(ctx context.Context) (int64, error)
	CreateCollectionRun(ctx context.Context, source string) (int64, error)
	FinishCollectionRun(ctx context.Context, arg FinishCollectionRunParams) error
	InsertExtractedArtifact(ctx context.Context, arg InsertExtractedArtifactParams) (int64, error)
	ListExistingNoticeSeqs(ctx context.Context, arg ListExistingNoticeSeqsParams) ([]string, error)
	ListHousingUnits(ctx context.Context, arg ListHousingUnitsParams) ([]ListHousingUnitsRow, error)
	ListSourceNotices(ctx context.Context, limit int32) ([]ListSourceNoticesRow, error)
	PromoteHousingUnitsQA(ctx context.Context) error
	UpsertAttachment(ctx context.Context, arg UpsertAttachmentParams) (int64, error)
	UpsertHousingUnit(ctx context.Context, arg UpsertHousingUnitParams) (int64, error)
	UpsertSourceBoard(ctx context.Context, arg UpsertSourceBoardParams) (int64, error)
	UpsertSourceNotice(ctx context.Context, arg UpsertSourceNoticeParams) (int64, error)
	UpsertStoredObject(ctx context.Context, arg UpsertStoredObjectParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
